#include <BlynkApiArduino.h>
#include <BlynkApiParticle.h>
#include <BlynkParticle.h>
#include <BlynkSimpleCC3000.h>
#include <BlynkSimpleCurieBLE.h>
#include <BlynkSimpleEnergiaEthernet.h>
#include <BlynkSimpleEnergiaWiFi.h>
#include <BlynkSimpleEsp32.h>
#include <BlynkSimpleEsp8266.h>
#include <BlynkSimpleEsp8266_SSL.h>
#include <BlynkSimpleEthernet.h>
#include <BlynkSimpleEthernet2.h>
#include <BlynkSimpleEthernetV2_0.h>
#include <BlynkSimpleFishino.h>
#include <BlynkSimpleIntelEdisonWiFi.h>
#include <BlynkSimpleLinkItONE.h>
#include <BlynkSimpleMKR1000.h>
#include <BlynkSimpleParticle.h>
#include <BlynkSimpleRedBearLab_BLE_Nano.h>
#include <BlynkSimpleRedBear_Duo.h>
#include <BlynkSimpleRedBear_Duo_BLE.h>
#include <BlynkSimpleRFduinoBLE.h>
#include <BlynkSimpleSerialBLE.h>
#include <BlynkSimpleShieldEsp8266.h>
#include <BlynkSimpleSimbleeBLE.h>
#include <BlynkSimpleStream.h>
#include <BlynkSimpleTinyDuino.h>
#include <BlynkSimpleUIPEthernet.h>
#include <BlynkSimpleUserDefined.h>
#include <BlynkSimpleWifi.h>
#include <BlynkSimpleWiFiShield101.h>
#include <BlynkSimpleWiFiShield101_SSL.h>
#include <BlynkSimpleWiFly.h>
#include <BlynkSimpleWildFire.h>
#include <BlynkSimpleYun.h>
#include <BlynkWidgets.h>
#include <BlynkWrongInclude.h>
#include <WidgetBridge.h>
#include <WidgetGPS.h>
#include <WidgetLCD.h>
#include <WidgetLED.h>
#include <WidgetRTC.h>
#include <WidgetSD.h>
#include <WidgetTable.h>
#include <WidgetTerminal.h>
#include <WidgetTimeInput.h>

#include <ArduinoOTA.h>

/**************************************************************
 * Blynk is a platform with iOS and Android apps to control
 * Arduino, Raspberry Pi and the likes over the Internet.
 * You can easily build graphic interfaces for all your
 * projects by simply dragging and dropping widgets.
 *
 *   Downloads, docs, tutorials: http://www.blynk.cc
 *   Blynk community:            http://community.blynk.cc
 *   Social networks:            http://www.fb.com/blynkapp
 *                               http://twitter.com/blynk_app
 *
 * Blynk library is licensed under MIT license
 *
 *
 **************************************************************
 * 
 * 
 *
 * WARNING :
 * For this example you'll need SimpleTimer library:
 *   https://github.com/jfturcot/SimpleTimer
 * Visit this page for more information:
 *   http://playground.arduino.cc/Code/SimpleTimer
 *
 * DHT11 ----pin 12
 *  
 *
 **************************************************************/

#define BLYNK_PRINT Serial    // Comment this out to disable prints and save space
#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>
#include <SimpleTimer.h>
#include <dht11.h>
dht11 DHT;
#define DHT11_PIN 12
// You should get Auth Token in the Blynk App.
// Go to the Project Settings (nut icon).
char auth[] = "xxxxxxxx"; //insert here your token generated by Blynk

SimpleTimer timer;

void setup()
{
  Serial.begin(9600); // See the connection status in Serial Monitor
   Blynk.begin(auth, "ssid", "password!"); //insert here your SSID and password
 
  // Setup a function to be called every second
  timer.setInterval(1000L, sendUptime);
}

// This function sends Arduino's up time every second to Virtual Pin (5).
// In the app, Widget's reading frequency should be set to PUSH. This means
// that you define how often to send data to Blynk App.
void sendUptime()
{
  // You can send any value at any time.
  // Please don't send more that 10 values per second.
  Blynk.virtualWrite(10, DHT.temperature); //virtual pin
  Blynk.virtualWrite(11, DHT.humidity); // virtual pin 
}

void loop()
{
  Blynk.run(); // Initiates Blynk
  timer.run(); // Initiates SimpleTimer
  int chk; 
  chk = DHT.read(DHT11_PIN);    // READ DATA
}


